# Generated by Django 3.2.23 on 2024-01-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'TelegramGroup',
                'verbose_name_plural': 'TelegramGroups',
            },
        ),
    ]
