# Generated by Django 3.2.23 on 2024-01-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20240110_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='bot_message',
            field=models.BooleanField(default=False),
        ),
    ]
